# Generated by Django 3.2.9 on 2022-05-14 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0007_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 15, 19, 38, 351455, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
